# .github/workflows/monthly-report.yml
name: Monthly Website Report

on:
  schedule:
    - cron: '0 6 1 * *' # Monthly on the 1st at 6AM UTC
  workflow_dispatch:     # Optional: allow manual runs

env:
  SITE_NAME: "clearview-drupal"
  SITE_URL: "https://clearviewlibrary.org"

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create report folder
        run: |
          mkdir -p docs/reports/

      - name: Set dynamic datestamp
        run: echo "DATESTAMP=$(date +'%Y-%m-%d')" >> "$GITHUB_ENV"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install tools
        run: |
          npm install
          npm ci
          npx playwright install

      
      - name: Run a11y scan
        continue-on-error: true
        run: node crawler.js --site_name=$SITE_NAME --start_url=$SITE_URL --datestamp=$DATESTAMP

      - name: Generate a11y reports
        continue-on-error: true
        run: node summary-reporter.js --site_name=$SITE_NAME --start_url=$SITE_URL --datestamp=$DATESTAMP

      - name: Configure Git for GitHub Actions
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Commit and Push Reports
        run: |
          git add docs
          git commit -m "Add reports for ${{ steps.date.outputs.date }}" || echo "No changes to commit"
          git push