# .github/workflows/monthly-report.yml
name: Monthly Website Report

on:
  schedule:
    - cron: '0 6 1 * *' # Monthly on the 1st at 6AM UTC
  workflow_dispatch:     # Optional: allow manual runs

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create report folder
        run: mkdir -p docs/reports/${{ steps.date.outputs.date }}
      
      - name: Run Lighthouse with GitHub Action
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: 'https://clearviewlibrary.org'
          outputDirectory: './docs/reports/${{ steps.date.outputs.date }}'
          uploadArtifacts: false
          configPath: '.lighthouserc.json'  # optional

      - name: Run broken link check
        run: |
          npm install linkinator
          npx linkinator https://clearviewlibrary.org --recursive --output ./docs/reports/${{ steps.date.outputs.date }}/broken-links.txt

      - name: Run pa11y accessibility check
        run: |
          npm install pa11y
          npx pa11y-ci https://clearviewlibrary.org --reporter html > ./docs/reports/${{ steps.date.outputs.date }}/pa11y.html

      - name: Commit reports
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add ./report
          git commit -m "Monthly report $(date +'%Y-%m-%d')"
          git push
