# .github/workflows/monthly-report.yml
name: Monthly Website Report

on:
  schedule:
    - cron: '0 6 1 * *' # Monthly on the 1st at 6AM UTC
  workflow_dispatch:     # Optional: allow manual runs

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create report folder
        run: mkdir -p docs/reports/${{ steps.date.outputs.date }}

      - name: Install Chromium Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ca-certificates \
            fonts-liberation \
            libappindicator3-1 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libcups2 \
            libdbus-1-3 \
            libgdk-pixbuf2.0-0 \
            libnspr4 \
            libnss3 \
            libx11-xcb1 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            xdg-utils \
            libgbm1 \
            libgtk-3-0
      
      - name: Run Lighthouse
        continue-on-error: true
        run: |
          npm install -g lighthouse
          lighthouse https://clearviewlibrary.org \
            --output html \
            --output-path ./docs/reports/${{ steps.date.outputs.date }}/lighthouse.html \
            --chrome-flags="--headless --no-sandbox --disable-gpu --disable-dev-shm-usage" \
            --quiet

      - name: Run Broken Link Checker (Linkinator)
        continue-on-error: true
        run: |
          npx linkinator https://clearviewlibrary.org \
            --recursive \
            --verbosity DEBUG \
            --timeout 10000 \
            --skip "mailto:,tel:" \
            --silent false \
            > ./docs/reports/${{ steps.date.outputs.date }}/broken-links.txt

      - name: Run Accessibility Audit with Pa11y CI
        continue-on-error: true
        run: |
          npm install -g pa11y-ci
          npx pa11y-ci --reporter html > ./docs/reports/${{ steps.date.outputs.date }}/pa11y.html

      - name: Commit reports
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add ./docs
          git commit -m "Monthly report $(date +'%Y-%m-%d')"
          git push
