# .github/workflows/monthly-report.yml
name: Monthly Website Report

on:
  schedule:
    - cron: '0 6 1 * *' # Monthly on the 1st at 6AM UTC
  workflow_dispatch:     # Optional: allow manual runs

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create report folder
        run: |
          mkdir -p docs/reports/

      - name: Install tools
        run: |
          npm install
          npx install playwright
      
      - name: Run a11y reports
        continue-on-error: true
        run: node a11y-run-all.js --site_name="clearview" --start_url="https://clearviewlibrary.org"

      - name: Configure Git for GitHub Actions
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Commit and Push Reports
        run: |
          git add docs
          git commit -m "Add reports for ${{ steps.date.outputs.date }}" || echo "No changes to commit"
          git push